language: node_js
node_js: node
script:
- npm run test
- |
  if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_EVENT_TYPE != "cron" ]; then
    echo "Not a Pull Request and on branch master so bumping version";
    frauci-update-version;
    export TRAVIS_TAG=$(frauci-get-version)
  fi
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUI
  - REPO_NAME=tabs
  # GITHUB_RELEASE_TOKEN
  - secure: H2r38DKESAlhvM07Wnip7fo7Hbh7SDOzwYrPdlc/pmyrFoEOdqZ/yovYWCZbNu4B65gI5k2yUXnDCVmbDU4JgtIjSJNcX9/2wg7OwIVBx2km5PKQwP9W3sUmuPAl0WLAbqh63DP/TH0I0xo9Bep7PvdkLPBccpdQu3Xo279kJcqH30l5BJX+fmICmIpvX3Cj5s7ujkImE341H4I7yRrWV7eZgy0DPME5L/xsXt7b/5ZKb6I2sCvmt1P2v8ChB8IZSNlunWPAe70IH8xFVZuMOb4frutW2PZ2ttqYLqra8RhRhFvE7ynq6XhMPAg9ka4D1pxfkvo1RfVg7E5/Vhp7ypM2bGJmjlskMnjiCMtMQ5rD4Y6P8YeNzGXg55cua55a0EmcbhKe8ITHN6PHcfEF55b8+TnztJ+pLfXWYTl6LYX1vhzKnAivqMAHcGSJSlpQMJ0rpIIwYvKdq6/x+KkZihamrVSIOKla0gJgbuCQQB2abVWV+/n+B7DVJaFjyjDLrXc6++w8KPFj3JaIqAjKDSv13UtQ/yQ7BzWYRYsQJLIui2Wn/A9DfHhkUNrjlSfCfdB3k1gMNOHVVv5uZGmp3/Z6kv57jR9IJedRdJxRS/FP/T8784wsIslUBimX2/LDDOmf8aZetcYXQ3jsNOiNjETxb15y0tSYdDAWslEqp/M=
